apiVersion: v1
kind: Secret
metadata:
  name: laundrypool-secret
type: Opaque
stringData:
  SECRET_KEY: "supersecretkeychange_me"
  # Add any other environment variables here, e.g., database URLs, Stripe keys, etc.